# Generated by Django 5.0.4 on 2024-05-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('gardening', 'Gardening'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('toys', 'Toys'), ('books', 'Books'), ('cosmetics', 'Cosmetics'), ('other', 'Other')], max_length=64),
        ),
    ]
